# Generated by Django 5.1.5 on 2025-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='stand_cover',
            field=models.ImageField(upload_to='media/stand_cover/'),
        ),
    ]
