# Generated by Django 6.0.3 on 2026-04-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="category",
        ),
        migrations.RemoveField(
            model_name="member",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
    ]
