# Generated by Django 5.1.5 on 2025-04-25 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('classe', models.CharField(choices=[('1ª', '1ª'), ('2ª', '2ª'), ('3ª', '3ª'), ('4ª', '4ª'), ('5ª', '5ª'), ('6ª', '6ª'), ('7ª', '7ª'), ('8ª', '8ª'), ('9ª', '9ª'), ('10ª', '10ª'), ('11ª', '11ª'), ('12ª', '12ª')], max_length=3)),
                ('turma', models.CharField(max_length=2)),
                ('course', models.CharField(choices=[('Informática', 'Informática'), ('Eletrônica', 'Eletrônica')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='competitor',
        ),
        migrations.RemoveField(
            model_name='category',
            name='end_date',
        ),
        migrations.AddField(
            model_name='category',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.member'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project_cover', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.project'),
        ),
        migrations.AddField(
            model_name='vote',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.DeleteModel(
            name='Competitor',
        ),
    ]
