# Generated by Django 5.1.5 on 2025-06-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stand_cover', models.ImageField(upload_to='stand_cover/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand', to='api.activity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand', to='api.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand', to='api.subcategory')),
            ],
        ),
    ]
