# Generated by Django 5.1.5 on 2025-06-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
