# Generated by Django 5.1.5 on 2025-06-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stand_stand_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='classe',
            field=models.CharField(choices=[('1ª', '1ª'), ('2ª', '2ª'), ('3ª', '3ª'), ('4ª', '4ª'), ('5ª', '5ª'), ('6ª', '6ª'), ('7ª', '7ª'), ('8ª', '8ª'), ('9ª', '9ª'), ('10ª', '10ª'), ('11ª', '11ª'), ('12ª', '12ª'), ('13ª', '13ª')], max_length=3),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/member_profiles/'),
        ),
    ]
