# Generated by Django 5.1.5 on 2025-04-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_member_remove_vote_competitor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='course',
            field=models.CharField(blank=True, choices=[('Informática', 'Informática'), ('Eletrônica', 'Eletrônica')], max_length=20, null=True),
        ),
    ]
