# Generated by Django 6.0.3 on 2026-04-06 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_member_category_remove_member_subcategory_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="vote",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="api.member",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="api.project",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="stand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="api.stand",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="vote",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="category",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="category_type",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="subcategory",
        ),
    ]
