# Generated by Django 5.1.5 on 2025-04-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_member_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(default=False, upload_to='members/'),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('project', 'Projeto'), ('expositor', 'Expositor')], default='project', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'category', 'vote_type')},
        ),
    ]
