# Generated by Django 6.0.4 on 2026-04-10 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_vote_unique_together_alter_vote_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="api.activity",
            ),
        ),
    ]
