# Generated by Django 5.1.5 on 2025-06-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_is_global'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='subcategory',
        ),
    ]
