# Generated by Django 5.1.5 on 2025-06-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_member_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='course',
            field=models.CharField(blank=True, choices=[('Informática', 'Informática'), ('Eletrônica', 'Eletrônica'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stand',
            name='stand_cover',
            field=models.ImageField(upload_to='stand_cover/'),
        ),
    ]
