# Generated by Django 6.0.4 on 2026-04-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_category_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="api.activity",
            ),
        ),
    ]
