# Generated by Django 6.0.4 on 2026-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_subcategory_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile_image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_cover",
            field=models.URLField(null=True),
        ),
    ]
