# Generated by Django 5.1.5 on 2025-05-01 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_voter_groups_remove_voter_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='finished',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Informática', 'Informática'), ('Eletrônica', 'Eletrônica'), ('Cantinho tecnológico', 'Cantinho tecnológico')], max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.activity'),
        ),
        migrations.AddField(
            model_name='vote',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'activity', 'category', 'vote_type')},
        ),
    ]
