# Generated by Django 5.2.5 on 2025-08-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_member_profile_image_alter_stand_stand_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
