# Generated by Django 6.0.4 on 2026-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_member_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile_image",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_cover",
            field=models.TextField(null=True),
        ),
    ]
