# Generated by Django 6.0.4 on 2026-04-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_member_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["voter", "project"], name="api_vote_voter_i_1b1b12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["voter", "member"], name="api_vote_voter_i_b5df28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["voter", "stand"], name="api_vote_voter_i_6078ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["project", "created_at"], name="api_vote_project_31bc9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["member", "created_at"], name="api_vote_member__727401_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["stand", "created_at"], name="api_vote_stand_i_47f38e_idx"
            ),
        ),
    ]
