# Generated by Django 5.2.5 on 2025-08-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_voter_code_generated_at_voter_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_cover',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.TextField(),
        ),
    ]
