# Generated by Django 6.0.5 on 2026-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_vote_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=models.CharField(max_length=100)),
        ),
    ]
