# Generated by Django 5.2.5 on 2025-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_project_project_cover_alter_member_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
