# Generated by Django 5.1.5 on 2025-06-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_member_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
