# Generated by Django 5.1.5 on 2025-06-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_category_description_remove_voter_google_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='member_profiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_cover',
            field=models.ImageField(blank=True, null=True, upload_to='project_covers/'),
        ),
    ]
